[files]
# The following files will be excluded from spell check during commits
extend-exclude = [
    "third_party",
    "patches",
    "build",
    "test/dataset/imikolov_test.py"
]

[default.extend-words]
# PaddlePaddle specific words
anc = 'anc'
arange = "arange"
astroid = 'astroid'
dout = "dout"
eles = 'eles'
grad = "grad"
lod = "lod"
Nce = "Nce"
Nd = "Nd"
ot = 'ot'
pash = 'pash'
UE = "UE"
unpacket = "unpacket"

# These words need to be fixed
assigend = 'assigend'
assined = 'assined'
assgin = 'assgin'
axises = 'axises'
Axises = 'Axises'
aixs = 'aixs'
beacuse = 'beacuse'
becasue = 'becasue'
Becasue = 'Becasue'
becuase = 'becuase'
blokc = 'blokc'
blcok = 'blcok'
bootom = 'bootom'
bondary = 'bondary'
branchs = 'branchs'
Broardcast = 'Broardcast'
Bradcast = 'Bradcast'
Boardcast = 'Boardcast'
Buitin = 'Buitin'
buitlin = 'buitlin'
buitin = 'buitin'
builded = 'builded'
ba = 'ba'
cahe = 'cahe'
Caculate = 'Caculate'
caculate = 'caculate'
calcualtion = 'calcualtion'
cacl = 'cacl'
cll = 'cll'
candiate = 'candiate'
cadidate = 'cadidate'
connot = 'connot'
CANN = 'CANN'
Cann = 'Cann'
cann = 'cann'
vart = 'vart'
checkings = 'checkings'
childs = 'childs'
Chunck = 'Chunck'
clen = 'clen'
Clas = 'Clas'
clas = 'clas'
compability = 'compability'
compatiblity = 'compatiblity'
Compitable = 'Compitable'
compatable = 'compatable'
compitable = 'compitable'
compling = 'compling'
comple = 'comple'
complition = 'complition'
complext = 'complext'
compsite = 'compsite'
configurated = 'configurated'
configed = 'configed'
confict = 'confict'
conjuction = 'conjuction'
conect = 'conect'
consequtive = 'consequtive'
consistant = 'consistant'
contraints = 'contraints'
contruction = 'contruction'
consructor = 'consructor'
comsume = 'comsume'
Continer = 'Continer'
contenst = 'contenst'
conter = 'conter'
ontext = 'ontext'
Continous = 'Continous'
contibute = 'contibute'
controled = 'controled'
contorl = 'contorl'
converage = 'converage'
Converage = 'Converage'
convertion = 'convertion'
Conver = 'Conver'
convience = 'convience'
coodinate = 'coodinate'
copyed = 'copyed'
Copyed = 'Copyed'
copys = 'copys'
corener = 'corener'
corrrect = 'corrrect'
Correspoding = 'Correspoding'
Cound = 'Cound'
coule = 'coule'
craete = 'craete'
craeted = 'craeted'
Creater = 'Creater'
creater = 'creater'
Currenly = 'Currenly'
curent = 'curent'
currnt = 'currnt'
Costum = 'Costum'
dateset = 'dateset'
dota = 'dota'
Datas = 'Datas'
DATAS = 'DATAS'
datas = 'datas'
delt = 'delt'
dealed = 'dealed'
deciamls = 'deciamls'
decalared = 'decalared'
decompse = 'decompse'
decompositing = 'decompositing'
defalut = 'defalut'
Defaule = 'Defaule'
defaut = 'defaut'
defualt = 'defualt'
defered = 'defered'
Defered = 'Defered'
defind = 'defind'
defeine = 'defeine'
defition = 'defition'
defination = 'defination'
delet = 'delet'
dependecies = 'dependecies'
dependecy = 'dependecy'
decprecated = 'decprecated'
derivated = 'derivated'
descripor = 'descripor'
deserailize = 'deserailize'
Destory = 'Destory'
DEIVCE = 'DEIVCE'
dictionnary = 'dictionnary'
diffrence = 'diffrence'
defferent = 'defferent'
differenciation = 'differenciation'
differnt = 'differnt'
diffrent = 'diffrent'
difficults = 'difficults'
dimensinal = 'dimensinal'
dimenstions = 'dimenstions'
dimenstion = 'dimenstion'
dimention = 'dimention'
demension = 'demension'
Direcly = 'Direcly'
direcly = 'direcly'
direcotory = 'direcotory'
direcotry = 'direcotry'
diabled = 'diabled'
diable = 'diable'
distingusih = 'distingusih'
distrubuted = 'distrubuted'
distibuted = 'distibuted'
dito = 'dito'
devide = 'devide'
documention = 'documention'
doens = 'doens'
doen = 'doen'
doubel = 'doubel'
dobule = 'dobule'
Dowloading = 'Dowloading'
downsteram = 'downsteram'
effeciently = 'effeciently'
effecient = 'effecient'
elemenents = 'elemenents'
elments = 'elments'
elimate = 'elimate'
alse = 'alse'
embeding = 'embeding'
emited = 'emited'
Enabel = 'Enabel'
enbale = 'enbale'
encouter = 'encouter'
endianess = 'endianess'
enfore = 'enfore'
entrys = 'entrys'
envirnment = 'envirnment'
environnement = 'environnement'
epoches = 'epoches'
EPOCHES = 'EPOCHES'
epslion = 'epslion'
eqaul = 'eqaul'
Errorr = 'Errorr'
exmaple = 'exmaple'
expection = 'expection'
excption = 'excption'
execuate = 'execuate'
exsit = 'exsit'
exsits = 'exsits'
expaned = 'expaned'
epxand = 'epxand'
Expexted = 'Expexted'
expolitation = 'expolitation'
extream = 'extream'
faild = 'faild'
Flase = 'Flase'
featue = 'featue'
feeded = 'feeded'
fetchs = 'fetchs'
fileds = 'fileds'
filterd = 'filterd'
fliter = 'fliter'
Fidn = 'Fidn'
Finded = 'Finded'
fisrt = 'fisrt'
Flattend = 'Flattend'
flattend = 'flattend'
flattern = 'flattern'
Flattern = 'Flattern'
filpped = 'filpped'
flaot = 'flaot'
follwed = 'follwed'
folowing = 'folowing'
fot = 'fot'
formater = 'formater'
formating = 'formating'
foramt = 'foramt'
formate = 'formate'
formt = 'formt'
forwrad = 'forwrad'
forwad = 'forwad'
forword = 'forword'
founf = 'founf'
framwork = 'framwork'
fre = 'fre'
frequence = 'frequence'
fron = 'fron'
fullfill = 'fullfill'
FUL = 'FUL'
funtions = 'funtions'
funcitons = 'funcitons'
Funcitons = 'Funcitons'
funtion = 'funtion'
fuction = 'fuction'
fucntion = 'fucntion'
Fuction = 'Fuction'
Funtion = 'Funtion'
funcion = 'funcion'
Funcion = 'Funcion'
futher = 'futher'
furture = 'furture'
guassian = 'guassian'
gloabl = 'gloabl'
graident = 'graident'
grammer = 'grammer'
grpah = 'grpah'
Greate = 'Greate'
groupped = 'groupped'
gard = 'gard'
GARD = 'GARD'
Halfs = 'Halfs'
hadler = 'hadler'
Hander = 'Hander'
hander = 'hander'
Hanlder = 'Hanlder'
happend = 'happend'
hardward = 'hardward'
hight = 'hight'
hepler = 'hepler'
helpe = 'helpe'
hge = 'hge'
homogenous = 'homogenous'
horizonal = 'horizonal'
identiy = 'identiy'
indentify = 'indentify'
implemention = 'implemention'
implementated = 'implementated'
implementd = 'implementd'
impliment = 'impliment'
implment = 'implment'
implicitely = 'implicitely'
Inproper = 'Inproper'
inconsistence = 'inconsistence'
uncorrectly = 'uncorrectly'
Indext = 'Indext'
Indexs = 'Indexs'
indexs = 'indexs'
indiates = 'indiates'
indeces = 'indeces'
inferrence = 'inferrence'
Infered = 'Infered'
infered = 'infered'
infering = 'infering'
informations = 'informations'
imformation = 'imformation'
infomation = 'infomation'
Infor = 'Infor'
infor = 'infor'
inheritted = 'inheritted'
initilization = 'initilization'
initilized = 'initilized'
initalized = 'initalized'
initalize = 'initalize'
intialize = 'intialize'
inital = 'inital'
Inouts = 'Inouts'
intputs = 'intputs'
inputed = 'inputed'
intput = 'intput'
Intput = 'Intput'
inser = 'inser'
insid = 'insid'
insepection = 'insepection'
intall = 'intall'
instanciate = 'instanciate'
Instrution = 'Instrution'
INSTUCTION = 'INSTUCTION'
instuction = 'instuction'
interger = 'interger'
intermidiate = 'intermidiate'
itermediate = 'itermediate'
interal = 'interal'
internel = 'internel'
instrinsics = 'instrinsics'
intristic = 'intristic'
invalied = 'invalied'
Invaid = 'Invaid'
invaild = 'invaild'
invalide = 'invalide'
iteratable = 'iteratable'
interated = 'interated'
Iteraion = 'Iteraion'
IIT = 'IIT'
iy = 'iy'
kenerl = 'kenerl'
kernerl = 'kernerl'
Kernal = 'Kernal'
kerenl = 'kerenl'
Keyward = 'Keyward'
keyward = 'keyward'
kinf = 'kinf'
kow = 'kow'
lable = 'lable'
lamda = 'lamda'
labmda = 'labmda'
lastest = 'lastest'
Lanuch = 'Lanuch'
lanuch = 'lanuch'
leyer = 'leyer'
learing = 'learing'
Leafs = 'Leafs'
leafs = 'leafs'
levle = 'levle'
linke = 'linke'
lsit = 'lsit'
lits = 'lits'
localy = 'localy'
Localy = 'Localy'
logarithmical = 'logarithmical'
Loggin = 'Loggin'
macor = 'macor'
mantain = 'mantain'
mak = 'mak'
manualy = 'manualy'
mannualy = 'mannualy'
maping = 'maping'
Maxinum = 'Maxinum'
maxmium = 'maxmium'
menas = 'menas'
momory = 'momory'
Meatadata = 'Meatadata'
miliseconds = 'miliseconds'
minimun = 'minimun'
Minium = 'Minium'
minumum = 'minumum'
modication = 'modication'
modifed = 'modifed'
modifing = 'modifing'
modifty = 'modifty'
moduels = 'moduels'
Modul = 'Modul'
Morevoer = 'Morevoer'
mutiple = 'mutiple'
mutiply = 'mutiply'
Mutiply = 'Mutiply'
multipy = 'multipy'
Multiplie = 'Multiplie'
Muti = 'Muti'
muti = 'muti'
mutexs = 'mutexs'
nams = 'nams'
namess = 'namess'
neccessary = 'neccessary'
Neet = 'Neet'
neet = 'neet'
neeed = 'neeed'
nedd = 'nedd'
negtive = 'negtive'
negetive = 'negetive'
nagative = 'nagative'
Neighboor = 'Neighboor'
neigbhors = 'neigbhors'
Neigbors = 'Neigbors'
neighor = 'neighor'
netwrok = 'netwrok'
normlized = 'normlized'
Normlized = 'Normlized'
normlize = 'normlize'
noraml = 'noraml'
numer = 'numer'
Numberic = 'Numberic'
occured = 'occured'
Ocurred = 'Ocurred'
occures = 'occures'
Fo = 'Fo'
fo = 'fo'
offets = 'offets'
offseted = 'offseted'
OLT = 'OLT'
olny = 'olny'
pn = 'pn'
Operants = 'Operants'
operants = 'operants'
oeprations = 'oeprations'
Opeartion = 'Opeartion'
operaion = 'operaion'
oppotunity = 'oppotunity'
optimzed = 'optimzed'
optmize = 'optmize'
optin = 'optin'
Optin = 'Optin'
rder = 'rder'
oreder = 'oreder'
orignal = 'orignal'
orginal = 'orginal'
onces = 'onces'
outter = 'outter'
outpus = 'outpus'
outputing = 'outputing'
outout = 'outout'
ouput = 'ouput'
outpout = 'outpout'
ouptut = 'ouptut'
Ouput = 'Ouput'
ouside = 'ouside'
overriden = 'overriden'
Overide = 'Overide'
overide = 'overide'
overrided = 'overrided'
Packge = 'Packge'
pacakage = 'pacakage'
padd = 'padd'
payed = 'payed'
parellel = 'parellel'
parm = 'parm'
Parm = 'Parm'
PARM = 'PARM'
paramters = 'paramters'
Paramters = 'Paramters'
paramter = 'paramter'
Paramater = 'Paramater'
paramete = 'paramete'
parmeter = 'parmeter'
paremeter = 'paremeter'
parrent = 'parrent'
parital = 'parital'
partitial = 'partitial'
Partitial = 'Partitial'
Partion = 'Partion'
partion = 'partion'
patition = 'patition'
passs = 'passs'
Passs = 'Passs'
pathes = 'pathes'
patten = 'patten'
Patten = 'Patten'
pattens = 'pattens'
precent = 'precent'
performace = 'performace'
perfomed = 'perfomed'
perfome = 'perfome'
presistable = 'presistable'
pyhsical = 'pyhsical'
pipline = 'pipline'
palce = 'palce'
Placment = 'Placment'
pleace = 'pleace'
Poniter = 'Poniter'
poped = 'poped'
positon = 'positon'
POSTION = 'POSTION'
postive = 'postive'
possiable = 'possiable'
potentialy = 'potentialy'
precending = 'precending'
Prepration = 'Prepration'
Prepar = 'Prepar'
preprocesser = 'preprocesser'
priorites = 'priorites'
probabalistic = 'probabalistic'
processer = 'processer'
proccess = 'proccess'
producted = 'producted'
progam = 'progam'
progrss = 'progrss'
propogated = 'propogated'
Propogation = 'Propogation'
protocal = 'protocal'
PROTOCAL = 'PROTOCAL'
pyrhon = 'pyrhon'
pthon = 'pthon'
qucik = 'qucik'
quitted = 'quitted'
runned = 'runned'
readed = 'readed'
recived = 'recived'
recevied = 'recevied'
reveived = 'reveived'
recieved = 'recieved'
recieves = 'recieves'
recive = 'recive'
receving = 'receving'
recommand = 'recommand'
recomplie = 'recomplie'
recored = 'recored'
Recusive = 'Recusive'
recusive = 'recusive'
recursivly = 'recursivly'
Recursivly = 'Recursivly'
reduntant = 'reduntant'
Refered = 'Refered'
refered = 'refered'
registed = 'registed'
regist = 'regist'
Regist = 'Regist'
Registe = 'Registe'
registe = 'registe'
REGIST = 'REGIST'
Regiter = 'Regiter'
releated = 'releated'
realease = 'realease'
relase = 'relase'
reomve = 'reomve'
Reoder = 'Reoder'
repeatly = 'repeatly'
repeate = 'repeate'
repalce = 'repalce'
represention = 'represention'
requied = 'requied'
Reqiured = 'Reqiured'
Requred = 'Requred'
requirments = 'requirments'
Reseting = 'Reseting'
reseted = 'reseted'
resouce = 'resouce'
retore = 'retore'
rewriten = 'rewriten'
rewrited = 'rewrited'
Runing = 'Runing'
runing = 'runing'
SMAE = 'SMAE'
satifies = 'satifies'
sclar = 'sclar'
sacle = 'sacle'
schduler = 'schduler'
sheduler = 'sheduler'
shedule = 'shedule'
scheule = 'scheule'
serach = 'serach'
seconde = 'seconde'
Seleceted = 'Seleceted'
sence = 'sence'
seperately = 'seperately'
seperate = 'seperate'
sepearate = 'sepearate'
seperating = 'seperating'
seperator = 'seperator'
sequnce = 'sequnce'
seqence = 'seqence'
sequece = 'sequece'
sequnece = 'sequnece'
sequentail = 'sequentail'
serailize = 'serailize'
settting = 'settting'
ser = 'ser'
setted = 'setted'
SEH = 'SEH'
seh = 'seh'
shoule = 'shoule'
shoud = 'shoud'
Singal = 'Singal'
Similiar = 'Similiar'
simular = 'simular'
Simle = 'Simle'
signle = 'signle'
Skiped = 'Skiped'
skiped = 'skiped'
smll = 'smll'
samll = 'samll'
somme = 'somme'
patial = 'patial'
Patial = 'Patial'
specificed = 'specificed'
splite = 'splite'
spliter = 'spliter'
spliting = 'spliting'
Spliting = 'Spliting'
splited = 'splited'
splitted = 'splitted'
Splited = 'Splited'
sqaure = 'sqaure'
sequeze = 'sequeze'
starup = 'starup'
statment = 'statment'
staticly = 'staticly'
staticaly = 'staticaly'
Stati = 'Stati'
STOPED = 'STOPED'
Stoped = 'Stoped'
stoped = 'stoped'
storeage = 'storeage'
sotring = 'sotring'
stragety = 'stragety'
strem = 'strem'
structed = 'structed'
sturcture = 'sturcture'
subsituted = 'subsituted'
subsitute = 'subsitute'
substitude = 'substitude'
substitue = 'substitue'
Subsitute = 'Subsitute'
Substitude = 'Substitude'
substract = 'substract'
Substract = 'Substract'
successed = 'successed'
sucessfully = 'sucessfully'
Succeess = 'Succeess'
Suger = 'Suger'
supportted = 'supportted'
supoort = 'supoort'
Supprot = 'Supprot'
suport = 'suport'
suppport = 'suppport'
SWTICH = 'SWTICH'
Swith = 'Swith'
sysyem = 'sysyem'
targt = 'targt'
Taget = 'Taget'
templat = 'templat'
temporaily = 'temporaily'
temporily = 'temporily'
Temperarily = 'Temperarily'
temporaly = 'temporaly'
Temperary = 'Temperary'
tenosr = 'tenosr'
iterm = 'iterm'
termiante = 'termiante'
ths = 'ths'
thi = 'thi'
Theoritical = 'Theoritical'
ther = 'ther'
thr = 'thr'
thge = 'thge'
Teh = 'Teh'
tne = 'tne'
thouse = 'thouse'
theads = 'theads'
thrads = 'thrads'
thre = 'thre'
THREAHOLD = 'THREAHOLD'
THORW = 'THORW'
timout = 'timout'
tiemout = 'tiemout'
TOOD = 'TOOD'
tood = 'tood'
TDOD = 'TDOD'
toghether = 'toghether'
Rto = 'Rto'
trainning = 'trainning'
Traning = 'Traning'
transforme = 'transforme'
transfered = 'transfered'
transfering = 'transfering'
tranfers = 'tranfers'
tranfer = 'tranfer'
Tranfer = 'Tranfer'
transfrom = 'transfrom'
tranform = 'tranform'
Tranpose = 'Tranpose'
tranpose = 'tranpose'
tigger = 'tigger'
trimed = 'trimed'
trival = 'trival'
Trye = 'Trye'
Tring = 'Tring'
tring = 'tring'
tunning = 'tunning'
TYPLE = 'TYPLE'
trun = 'trun'
tyep = 'tyep'
tpye = 'tpye'
unchangable = 'unchangable'
Undefind = 'Undefind'
unser = 'unser'
UNEXPECT = 'UNEXPECT'
Unifrom = 'Unifrom'
uninitialzed = 'uninitialzed'
Uniqe = 'Uniqe'
unqiue = 'unqiue'
uniqe = 'uniqe'
unkown = 'unkown'
unkonwn = 'unkonwn'
Unkown = 'Unkown'
unsupport = 'unsupport'
upsupported = 'upsupported'
Unsupport = 'Unsupport'
UNSUPPORT = 'UNSUPPORT'
unziped = 'unziped'
udpated = 'udpated'
upgarde = 'upgarde'
uptream = 'uptream'
ues = 'ues'
unsed = 'unsed'
uesd = 'uesd'
usefull = 'usefull'
usless = 'usless'
vaccum = 'vaccum'
valud = 'valud'
VAILD = 'VAILD'
valus = 'valus'
valuse = 'valuse'
Varible = 'Varible'
varaible = 'varaible'
vecotr = 'vecotr'
verson = 'verson'
vesion = 'vesion'
Vetical = 'Vetical'
vunerability = 'vunerability'
varn = 'varn'
warpped = 'warpped'
warpper = 'warpper'
Warpper = 'Warpper'
vas = 'vas'
wheather = 'wheather'
wether = 'wether'
Wether = 'Wether'
wieghts = 'wieghts'
werid = 'werid'
whe = 'whe'
Wheter = 'Wheter'
whther = 'whther'
whill = 'whill'
whos = 'whos'
wil = 'wil'
wll = 'wll'
wiil = 'wiil'
witk = 'witk'
Wih = 'Wih'
wih = 'wih'
worke = 'worke'
workround = 'workround'
worksapce = 'worksapce'
wrk = 'wrk'
wrappered = 'wrappered'
wraper = 'wraper'
wraping = 'wraping'
Writter = 'Writter'
writed = 'writed'
